# Notes: Run this docker compose file if you want to build image yourself
#   sudo docker compose -f build-docker-compose.yaml up -d --build --force-recreate

version: '3.9'

services:
  frigate2telegram:
    build:
      context: .
    image: frigate2telegram
    container_name: frigate2telegram
    volumes:
      - ./:/config
      - ./logs:/logs
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped