# Notes: Run this docker compose file from the custom_docker folder as shown below:
#   sudo docker compose up -d
# To rebuild without deleting whole image:
#   sudo docker compose up -d --build --force-recreate

version: '3.9'

services:
  frigate2telegram:
    build:
      context: .
    image: frigate2telegram
    container_name: frigate2telegram
    volumes:
      - ./:/config
      - ./logs:/logs
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped