name: Build and publish a Docker image to Github Packages

on:
  push:
    tags:
      - '*'
    #branches:
     # - release

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Echo some information
        run: |
          echo "Tag: github.ref_name: ${{ github.ref_name }}"
          echo "Base: github.base_ref: ${{ github.base_ref }}"
      - name: Build and push Docker image
        run: |
          docker login --username deeptanshupatel --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker build . -t ghcr.io/deeptanshupatel/frigate2telegram:${{ github.ref_name }} -t ghcr.io/deeptanshupatel/frigate2telegram:v$(TZ="America/Chicago" date +'%Y%m%d.%H%M%S') -t ghcr.io/deeptanshupatel/frigate2telegram
          docker push ghcr.io/deeptanshupatel/frigate2telegram --all-tags
